site: Big Rapids Chess

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  lessons:
    output: true
    permalink: /lesson/:slug
  resources:
    output: true
    permalink: /resource/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "lessons"
    values:
      layout: "lesson"
  -
    scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 3
paginate_path: "/blog/page:num/"
